name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: json-server
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and export to Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ env.IMAGE_NAME }}
    - name: Build container
      run: |
        docker build -t ${{ env.IMAGE_NAME }} .
    - name: Extract json-server version
      run: |
        echo "JSON_SERVER_VERSION=$(docker run --rm ${{ env.IMAGE_NAME }} -v)" >> $GITHUB_ENV
    - name: Tag & Push
      run: |
        docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.JSON_SERVER_VERSION }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.JSON_SERVER_VERSION }}
    - name: Tag & Push to Github registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.JSON_SERVER_VERSION }}
          docker tag ${{ env.IMAGE_NAME }} $IMAGE_ID
          docker push $IMAGE_ID
